//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloonLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Services_Customers = new HashSet<Services_Customers>();
        }
    
        public int Id { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public Nullable<System.DateTime> Bday { get; set; }
        public string Mail { get; set; }
        public string Phone { get; set; }
        public string Bonus { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date_of_registration { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Id_tag { get; set; }
    
        public virtual Tag Tag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services_Customers> Services_Customers { get; set; }
    }
}
