//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySaloonLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_of_pay
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_of_pay { get; set; }
        public Nullable<int> Id_product { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Id_Service_Customer { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Services_Customers Services_Customers { get; set; }
    }
}
